name: Spring Boot Docker Demo CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Build Docker image
      run: docker build -t spring-docker-demo .
      
    - name: Check Docker image
      run: docker image inspect spring-docker-demo

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      id: dependency-check
      with:
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --enableExperimental
    
    - name: Upload dependency check report
      uses: actions/upload-artifact@master
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/reports
    
    - name: Docker security scan with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'spring-docker-demo'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
